### PR TITLE
Better greetings

### PR DESCRIPTION
**Pull request by KimberlyBautista**
I didn't test this code but my dog says it's fine.

### CODE REVIEW

**Comment by KimberlyBautista** [comment]
@shajinzheng look at my changes pls

**Comment by shajinzheng** [comment]
Let's test in production 👍

**Comment by KimberlyBautista** [comment]
@shajinzheng pls give me a ship it lol

**Comment by shajinzheng** [comment]
lgtm

**Review by shajinzheng — APPROVED** [review]

**Pull request merged**
